In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
x = np.arange(2, 6).reshape(4)

In [3]:
x

array([2, 3, 4, 5])

In [4]:
x.shape

(4,)

In [5]:
x = np.arange(2, 10).reshape(2, 4)

In [6]:
x.shape

(2, 4)

In [7]:
x[0]

array([2, 3, 4, 5])

In [8]:
x[0, :]

array([2, 3, 4, 5])

In [9]:
x[0,]

array([2, 3, 4, 5])

In [10]:
x.ndim

2

In [11]:
x.dtype

dtype('int64')

In [12]:
x[1,]

array([6, 7, 8, 9])

In [13]:
x = np.arange(24).reshape(4, 3, 2)

In [14]:
x.shape

(4, 3, 2)

In [30]:
x


array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [28]:
np.__version__

'1.23.5'

In [31]:
d = [12.23, 13.32, 100, 36.32]

In [32]:
d = np.array(d)

In [33]:
d.ndim

1

In [35]:
d = np.arange(2, 11).reshape(3, 3)

In [36]:
d.shape

(3, 3)

In [37]:
d

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [43]:
d = np.zeros(10)

In [44]:
d[6] = 11

In [45]:
d

array([ 0.,  0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.])

In [47]:
a = np.arange(12, 38)

In [48]:
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37])

In [49]:
np.arange(12, 39)

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38])

In [50]:
a[::-1]

array([37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21,
       20, 19, 18, 17, 16, 15, 14, 13, 12])

In [51]:
a.astype('float')

array([12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.,
       25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37.])

In [59]:
d0 = np.ones((3, 5))

In [60]:
d0 

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [61]:
d0[1, :] = 0

In [62]:
d0

array([[1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.]])

In [63]:
e0 = np.ones((3, 3))

In [64]:
e0

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [67]:
np.vstack((np.zeros(3), e0, np.zeros(3)))

array([[0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.]])

In [70]:
np.array([1, 2, 3, 4, 5, 6, 7, 8
          ])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [79]:
np.array([[8, 4, 6], [1, 2, 3]])

array([[8, 4, 6],
       [1, 2, 3]])

In [80]:
append_arr  = np.arange(40, 100, 10)

In [90]:
append_arr.tolist()

[40, 50, 60, 70, 80, 90]

In [99]:
 t = [10, 20, 30]

In [100]:
t

[10, 20, 30]

In [95]:
t.append(append_arr.tolist())

In [96]:
t

[10, 20, 30, [40, 50, 60, 70, 80, 90]]

In [101]:
t.extend(append_arr.tolist())

In [102]:
t

[10, 20, 30, 40, 50, 60, 70, 80, 90]

In [103]:
np.empty((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 0., 0., 0.]])

In [104]:
np.ones((3, 3)) * 6

array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])

In [106]:
q =[ 1.00000000+0.j, 0.70710678+0.70710678j]

In [110]:
np.iscomplex(q)

array([False,  True])

In [111]:
q0 = q[0]
q1 = q[1]

In [112]:
q0

(1+0j)

In [113]:
q1

(0.70710678+0.70710678j)

In [114]:
q1.imag

0.70710678

In [115]:
q1.real

0.70710678

In [116]:
q0.real

1.0

In [117]:
q0.imag

0.0

In [118]:
a = np.arange(3)

In [119]:
a

array([0, 1, 2])

In [120]:
a.size

3

In [122]:
a.itemsize

8

In [123]:
a.size*a.itemsize

24

In [125]:
a =np.array(((1,0,0), (0,1,0), (0,0,1)), dtype=float) 

In [126]:
a = np.array([0,  0, 0])

In [127]:
a

array([0, 0, 0])

In [128]:
a = np.array([[0, 0, 0]])

In [129]:
a

array([[0, 0, 0]])

In [140]:
a, b = np.zeros((3,)), np.ones((3,))

In [141]:
a

array([0., 0., 0.])

In [142]:
b

array([1., 1., 1.])

In [143]:
a.dtype = 'int'

In [134]:
a

array([0, 0, 0])

In [138]:
b.dtype = 'int'

In [144]:
b

array([1., 1., 1.])

In [145]:
b.astype('int')

array([1, 1, 1])

In [219]:
a = np.linspace(1, 48, 48).reshape(3, 4, 4)

In [220]:
a.size

48

In [221]:
a

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]],

       [[17., 18., 19., 20.],
        [21., 22., 23., 24.],
        [25., 26., 27., 28.],
        [29., 30., 31., 32.]],

       [[33., 34., 35., 36.],
        [37., 38., 39., 40.],
        [41., 42., 43., 44.],
        [45., 46., 47., 48.]]])

In [222]:
a[(1, 0, 3) ]

20.0

In [153]:
a[1, 0, 3]

20.0

In [154]:
a[1][0, 3]

20.0

In [156]:
a[0, 2, :]

array([ 9., 10., 11., 12.])

In [157]:
a[2]

array([[33., 34., 35., 36.],
       [37., 38., 39., 40.],
       [41., 42., 43., 44.],
       [45., 46., 47., 48.]])

In [158]:
a[:, 1, :2]

array([[ 5.,  6.],
       [21., 22.],
       [37., 38.]])

In [223]:
a[2, :, -1:-3:-1]

array([[36., 35.],
       [40., 39.],
       [44., 43.],
       [48., 47.]])

In [224]:
p =[2, 3, 4, 5]

In [225]:
p[::-1]

[5, 4, 3, 2]

In [226]:
p[2:0:-1]

[4, 3]

In [227]:
p[0:4]

[2, 3, 4, 5]

In [228]:
a0 = ['spam', 'egg', 'bacon', 'tomato', 'ham', 'lobster']

In [230]:
a0[-1:-3:-1]

['lobster', 'ham']

In [234]:
a[:, ::-1, 0]

array([[13.,  9.,  5.,  1.],
       [29., 25., 21., 17.],
       [45., 41., 37., 33.]])

In [235]:
a

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]],

       [[17., 18., 19., 20.],
        [21., 22., 23., 24.],
        [25., 26., 27., 28.],
        [29., 30., 31., 32.]],

       [[33., 34., 35., 36.],
        [37., 38., 39., 40.],
        [41., 42., 43., 44.],
        [45., 46., 47., 48.]]])

In [252]:
ia = np.array(((0,0), (0,2)))
ja = np.array(((0,0), (2,3)))
za = np.array(((0,3), (3, 3)))

In [253]:
a

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]],

       [[17., 18., 19., 20.],
        [21., 22., 23., 24.],
        [25., 26., 27., 28.],
        [29., 30., 31., 32.]],

       [[33., 34., 35., 36.],
        [37., 38., 39., 40.],
        [41., 42., 43., 44.],
        [45., 46., 47., 48.]]])

In [254]:
a[ia, ja, za]

array([[ 1.,  4.],
       [12., 48.]])

In [255]:
pp = np.linspace(0, 2, 100)

In [256]:
pp[(pp>= 0) & (pp <=1)] 

array([0.        , 0.02020202, 0.04040404, 0.06060606, 0.08080808,
       0.1010101 , 0.12121212, 0.14141414, 0.16161616, 0.18181818,
       0.2020202 , 0.22222222, 0.24242424, 0.26262626, 0.28282828,
       0.3030303 , 0.32323232, 0.34343434, 0.36363636, 0.38383838,
       0.4040404 , 0.42424242, 0.44444444, 0.46464646, 0.48484848,
       0.50505051, 0.52525253, 0.54545455, 0.56565657, 0.58585859,
       0.60606061, 0.62626263, 0.64646465, 0.66666667, 0.68686869,
       0.70707071, 0.72727273, 0.74747475, 0.76767677, 0.78787879,
       0.80808081, 0.82828283, 0.84848485, 0.86868687, 0.88888889,
       0.90909091, 0.92929293, 0.94949495, 0.96969697, 0.98989899])

In [261]:
N=5

magic_square = np.zeros((N, N), dtype=int)
n = 1
i, j = 0, N//2

while n <= N**2:
    magic_square[i, j] = n
    n +=1
    newi, newj = (i-1) % N, (j+1)%N
    if magic_square[newi, newj]:
        i +=1
    else:
        i, j = newi, newj

print(magic_square)

[[17 24  1  8 15]
 [23  5  7 14 16]
 [ 4  6 13 20 22]
 [10 12 19 21  3]
 [11 18 25  2  9]]


In [263]:
def magic_checksum(N):
    return N * (N**2 +1)/2

In [264]:
magic_checksum(5)

65.0

In [267]:
sum(magic_square.diagonal())

65

In [268]:
for row in magic_square:
    print(sum(row))

65
65
65
65
65


In [269]:
for col in range(5):
    print(sum(magic_square[:, col]))

65
65
65
65
65


In [271]:
checker = np.arange(1, N**2+1)

In [272]:
checker

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [273]:
base_arr = magic_square.ravel()

In [275]:
base_arr.sort()

In [276]:
checker == base_arr

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [277]:
np.allclose(checker, base_arr)

True

In [279]:
mon= np.arange(1, 40, 2)

In [280]:
np.all(np.diff(mon)>=0)

True

In [ ]:
The dtypes of scalars and arrays

Question Q6.1.11
The dtype np.uint8 represents an unsigned integer in 8 bits. Its value may therefore be in the range 0−255
.Explain the following behaviour
