In [1]:
import numpy as np

In [3]:
np.array(((1,0, 0), (0,1, 0), (0, 0, 1)), dtype=float)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
 b , a= np.ones((3, )),  np.zeros((3, ))

In [5]:
a.astype('int')

array([0, 0, 0])

In [6]:
a = np.linspace(1, 48, 48).reshape(3, 4, 4)

In [7]:
a

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]],

       [[17., 18., 19., 20.],
        [21., 22., 23., 24.],
        [25., 26., 27., 28.],
        [29., 30., 31., 32.]],

       [[33., 34., 35., 36.],
        [37., 38., 39., 40.],
        [41., 42., 43., 44.],
        [45., 46., 47., 48.]]])

In [8]:
a[(1, 0, 3)]

20.0

In [9]:
a[0, 2, :]

array([ 9., 10., 11., 12.])

In [10]:
a[2]

array([[33., 34., 35., 36.],
       [37., 38., 39., 40.],
       [41., 42., 43., 44.],
       [45., 46., 47., 48.]])

In [11]:
a[:, 1, :2]

array([[ 5.,  6.],
       [21., 22.],
       [37., 38.]])

In [26]:
a[2, :, (3, 0)]

array([[36., 40., 44., 48.],
       [33., 37., 41., 45.]])

In [27]:
a[:, ::-1, 0]

array([[13.,  9.,  5.,  1.],
       [29., 25., 21., 17.],
       [45., 41., 37., 33.]])

In [28]:
a

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]],

       [[17., 18., 19., 20.],
        [21., 22., 23., 24.],
        [25., 26., 27., 28.],
        [29., 30., 31., 32.]],

       [[33., 34., 35., 36.],
        [37., 38., 39., 40.],
        [41., 42., 43., 44.],
        [45., 46., 47., 48.]]])

In [32]:
print(a[0, 0, 0])
print(a[0, 0, 3])

1.0
4.0


In [33]:
a[(0,0),(0,0),(0,3)]

array([1., 4.])

In [36]:
ia = np.array(((0, 0), (2, 2)))
ja = np.array(((0, 0), (3,3)))
za = np.array(((0,3), (0, 3)))

In [ ]:
a[(2, 3, 0), (2, 3, 3 )]

In [34]:
a[(2,2), (3, 3), (0, 3)]

array([45., 48.])

In [37]:
a[ia, ja, za]

array([[ 1.,  4.],
       [45., 48.]])

In [39]:
a = np.random.rand(4,4)*2

In [40]:
a

array([[0.31056095, 1.95529295, 1.70176653, 0.4536323 ],
       [1.8862577 , 0.07322627, 0.39307017, 0.42391245],
       [1.24764424, 1.02372178, 1.91509674, 0.15181974],
       [1.2405511 , 1.2675003 , 1.11758743, 1.11192305]])

In [ ]:
# Values between 0.5 and 1.5

In [42]:
b = (a>= 0.5) & (a<=1.5)

In [44]:
b.astype(int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 1, 0, 0],
       [1, 1, 1, 1]])

In [60]:
ms =np.array([[17, 24,  1,  8, 15],
 [23,  5,  7, 14, 16],
 [ 4,  6, 13, 20, 22],
 [10, 12, 19, 21,  3],
 [11, 18, 25,  2,  9]])

In [51]:
d = ms.ravel()

In [52]:
checker = np.arange(1, 26)

In [54]:
d.sort()

In [56]:
np.allclose(checker , d)

True

In [57]:
all(checker == d)

True

In [64]:
65 == ms.sum(axis=0)

array([ True,  True,  True,  True,  True])

In [65]:
b = np.random.randn(4,5,6)

In [66]:
b

array([[[ 1.50207808e+00,  4.55333251e-01,  8.52576969e-01,
         -3.33290676e-03,  4.78891757e-02, -7.80349408e-01],
        [ 1.30715104e+00, -1.97575662e+00, -5.62290267e-01,
          1.55876052e+00, -1.64605056e-01, -3.43224968e-01],
        [-1.59113123e+00, -8.53761843e-01,  5.10889072e-01,
          7.00266645e-01, -7.54211462e-01, -7.75330838e-01],
        [-1.53526286e+00,  2.12374062e-01,  2.70745007e-01,
         -8.29798887e-01, -1.57100959e+00,  2.99791962e+00],
        [ 7.11146941e-01,  8.36925194e-01,  2.12063764e+00,
         -5.11097579e-01, -4.51666551e-01,  6.42288447e-01]],

       [[-7.14736806e-01,  1.11424514e+00,  4.75261622e-01,
         -2.47332987e-01,  2.44054113e+00,  1.42212406e+00],
        [ 4.80801796e-01,  1.40391201e+00, -3.07867992e-01,
          1.18818212e+00, -1.53944784e-01, -1.93677835e+00],
        [ 4.57893279e-01,  8.89716390e-01,  1.42235030e-01,
         -1.61460824e+00,  6.11112358e-01, -8.26994283e-02],
        [-1.48374558e+00, -1.1

In [70]:
# Give me the number of elements in b
np.product(b.shape)

120